"""organization_scaling_erd

Revision ID: d1f1356f1a35
Revises: 0003_sessions_inactivity
Create Date: 2026-10-05 16:57:53.387463+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f1356f1a35'
down_revision: Union[str, None] = '0003_sessions_inactivity'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_workflow_name'), 'workflow_runs', ['workflow_name'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hours_info', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_city'), 'clinics', ['city'], unique=False)
    op.create_index(op.f('ix_clinics_organization_id'), 'clinics', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('lead_source_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_clinic_id'), 'leads', ['clinic_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('team_member_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_clinic_id'), 'slots', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_slots_start_time'), 'slots', ['start_time'], unique=False)
    op.create_index(op.f('ix_slots_team_member_id'), 'slots', ['team_member_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_user_id'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_clinic_id'), 'tasks', ['clinic_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_id', sa.String(length=50), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.String(length=100), nullable=True),
    sa.Column('team_member_id', sa.Uuid(), nullable=True),
    sa.Column('slot_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_full_name', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_clinic_id'), 'bookings', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_bookings_confirmation_id'), 'bookings', ['confirmation_id'], unique=True)
    op.create_index(op.f('ix_bookings_preferred_date'), 'bookings', ['preferred_date'], unique=False)
    op.drop_constraint(op.f('uq_appointments_confirmation_id'), 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_confirmation_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_confirmation_id'), 'appointments', ['confirmation_id'], unique=True)
    op.drop_column('appointments', 'has_insurance')
    op.drop_column('appointments', 'insurance_provider')
    op.add_column('organizations', sa.Column('primary_color', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('secondary_color', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('background_color', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('primary_font', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('secondary_font', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', type_='unique')
    op.drop_constraint(op.f('uq_services_slug'), 'services', type_='unique')
    op.add_column('team_members', sa.Column('clinic_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_team_members_clinic_id'), 'team_members', ['clinic_id'], unique=False)
    op.create_foreign_key('fk_team_members_clinic_id_clinics', 'team_members', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('clinic_id', sa.Uuid(), nullable=True))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_foreign_key('fk_users_clinic_id_clinics', 'users', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_clinic_id_clinics', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'clinic_id')
    op.drop_constraint('fk_team_members_clinic_id_clinics', 'team_members', type_='foreignkey')
    op.drop_index(op.f('ix_team_members_clinic_id'), table_name='team_members')
    op.drop_column('team_members', 'clinic_id')
    op.create_unique_constraint(op.f('uq_services_slug'), 'services', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('organizations', 'secondary_font')
    op.drop_column('organizations', 'primary_font')
    op.drop_column('organizations', 'background_color')
    op.drop_column('organizations', 'secondary_color')
    op.drop_column('organizations', 'primary_color')
    op.add_column('appointments', sa.Column('insurance_provider', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('has_insurance', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_appointments_confirmation_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_confirmation_id'), 'appointments', ['confirmation_id'], unique=False)
    op.create_unique_constraint(op.f('uq_appointments_confirmation_id'), 'appointments', ['confirmation_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_bookings_preferred_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_confirmation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_clinic_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_tasks_clinic_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_slots_team_member_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_start_time'), table_name='slots')
    op.drop_index(op.f('ix_slots_clinic_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_clinic_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_clinics_organization_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_city'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_workflow_runs_workflow_name'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('lead_sources')
    op.drop_table('announcements')
    # ### end Alembic commands ###
